---
- name: System setup
  hosts: all
  become: true

  vars:
    # Define common packages (same name across distributions)
    common_packages:
      - net-tools
      - curl
      - vim
      - git
      - traceroute
      - tcpdump
      - unzip
      - tar
      - rsync
      - tmux
      - nano
      - tree
      - bzip2
      - python3
      - bat
      - tldr
      - locate
      - htop
    # Define packages specific to Red Hat
    redhat_packages:
      - firewalld
      - bind-utils
    # Define packages specific to Ubuntu
    ubuntu_packages:
      - ufw
      - bind9-utils
    # Define ports to allow in the firewall
    allowed_ports:
      - 22
    # User variables
    new_user: sysadm
    new_user_password: "{{ 'SysAdmStrongPass123!' | password_hash('sha512') }}"

  tasks:
    - name: Update the system (Red Hat)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update the system (Ubuntu)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Install common packages
      package:
        name: "{{ common_packages }}"
        state: present

    - name: Install Red Hat-specific packages
      yum:
        name: "{{ redhat_packages }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Ubuntu-specific packages
      apt:
        name: "{{ ubuntu_packages }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Allow required ports (Red Hat)
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
      loop: "{{ allowed_ports }}"
      notify: reload_firewalld
      when: ansible_os_family == "RedHat"

    - name: Allow required ports (Ubuntu)
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: "{{ allowed_ports }}"
      when: ansible_os_family == "Debian"

    - name: Enable and start the firewall (Red Hat)
      service:
        name: firewalld
        state: started
        enabled: true
      when: ansible_os_family == "RedHat"

    - name: Enable and start the firewall (Ubuntu)
      ufw:
        state: enabled
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Add a new user
      user:
        name: "{{ new_user }}"
        password: "{{ new_user_password | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Grant sudo privileges to the new user
      copy:
        dest: "/etc/sudoers.d/{{ new_user }}"
        content: "{{ new_user }} ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: 0440

    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify: restart_sshd

  handlers:
    - name: reload_firewalld
      service:
        name: firewalld
        state: reloaded

    - name: restart_sshd
      service:
        name: sshd
        state: restarted
