- name: Initialize Kubernetes Control Plane
  hosts: controlplane
  become: true
  vars:
    pod_network_cidr: "10.244.0.0/16"  # Define la red de pods aquí
    username: "laura"
  tasks:
    - name: Check if Kubernetes cluster is initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeadm_init

    - name: Initialize Kubernetes cluster
      command: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_output
      when: not kubeadm_init.stat.exists

    - name: Save kubeadm init output
      copy:
        content: "{{ kubeadm_output.stdout }}"
        dest: /root/kubeadm-init.out
      when: kubeadm_output is defined

    - name: Display kubeadm init output
      debug:
        msg: "{{ kubeadm_output.stdout }}"
      when: kubeadm_output is defined

    - name: Create .kube directory for root
      file:
        path: "/root/.kube"
        state: directory
        mode: '0755'

    - name: Copy admin.conf to root's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/root/.kube/config"
        owner: root
        group: root
        mode: '0644'
      when: kubeadm_init.stat.exists

    - name: Create .kube directory for user {{ username }}
      file:
        path: "/home/{{ username }}/.kube"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ username }}/.kube/config"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0644'
      when: kubeadm_init.stat.exists