---
- name: Add argo cd
  hosts: controlplane
  become: yes
  vars:
    argo_manifest: "https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"

  tasks:

    - name: Add argo namespace
      command: kubectl create namespace argocd
      register: argo_result
      retries: 5
      delay: 10
      until: argo_result.rc == 0
      ignore_errors: yes

    - name: Apply argo manifest
      command: kubectl apply -n argocd -f {{ argo_manifest }}
      register: argo_result
      retries: 5
      delay: 10
      until: argo_result.rc == 0
      ignore_errors: yes

    - name: Verify argo was applied
      debug:
        msg: "Argo CD was applied."
      when: argo_result.rc == 0