- name: Add Worker Nodes - Join Cluster
  hosts: all:!controlplane
  become: true
  vars:
    control_plane_ip: "192.168.5.191"
    token: "flo6rz.3wy9i8tywnywdfhc"
    discovery_hash: "sha256:1e3839910338ceab59fb27e0fb40df959eb6f16d850df607cb1949e676b500c6"
  tasks:
    - name: Join worker to Kubernetes cluster
      shell: >
        kubeadm join {{ control_plane_ip }}:6443 --token {{ token }} --discovery-token-ca-cert-hash {{ discovery_hash }}

